version: "3.1"
services:

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    working_dir: /application
    volumes:
      - .:/application
      - ./storage-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=databasename
      - MYSQL_USER=databaseuser
      - MYSQL_PASSWORD=123456
    ports:
      - "8083:3306"

  

  web:
    image: nginx:alpine
    container_name: web
    working_dir: /application
    volumes:
     - .:/application
     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8081:80"

  php:
    build: phpdocker/php-fpm
    container_name: php
    working_dir: /application
    volumes:
      # - ./server:/application
    - ./api:/application
    - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
